export const USER_PHOTOS_API = 'USER_PHOTOS_API'
export const USER_PHOTOS_API_SUCCESS = 'USER_PHOTOS_API_SUCCESS'
export const USER_PHOTOS_API_ERROR = 'USER_PHOTOS_API_ERROR'

export const POPULAR_PHOTOS_API = 'POPULAR_PHOTOS_API'
export const POPULAR_PHOTOS_API_SUCCESS = 'POPULAR_PHOTOS_API_SUCCESS'
export const POPULAR_PHOTOS_API_ERROR = 'POPULAR_PHOTOS_API_ERROR'